version: "3"
services:
  acapy:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-nightly
    #image: acapy-test
    ports:
      - "3001:3001"
    command: >
      start
        --label Alice
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://acapy:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --no-ledger
        --wallet-type askar
        --wallet-name alice
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --emit-did-peer-4
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  afj:
    image: afj-json-rpc
    build: afj
    ports:
      - "3000:3000"
    environment:
      AFJ_MESSAGE_PORT: 3001
      AFJ_ENDPOINT: "http://afj:3001"
    volumes:
      - ./afj/index.ts:/usr/src/app/index.ts:z
    healthcheck:
      test: nc -z 0.0.0.0 3000
      start_period: 1s
      interval: 3s
      timeout: 5s
      retries: 5

  tests:
    container_name: runner
    build: .
    environment:
      AFJ_HOST: afj
      AFJ_PORT: 3000
      ACAPY_HOST: acapy
      ACAPY_PORT: 3001
    volumes:
      - ./tests:/usr/src/app/tests:z
    command: pytest
    depends_on:
      acapy:
        condition: service_healthy
      afj:
        condition: service_healthy
